# Generated by Django 3.2.8 on 2021-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.TextField(max_length=300)),
                ('referred_by', models.CharField(max_length=30)),
                ('customer_remarks', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
