# Generated by Django 3.2.8 on 2021-12-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
